version: '3'

services:
  toolkit-ci-build:
    image: microsoft/aspnetcore-build:2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./SQLToolkit/SQLToolkit/SQLToolkit.csproj && dotnet publish ./SQLToolkit/SQLToolkit/SQLToolkit.csproj -c Release -r win10-x64"

